### ISSUE TITLE
Severe formatting bug in Chinese translation of the docs

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-website#95]
https://casbin.org/docs/zh-CN/syntax-for-models#policy-effect定义

![image](https://user-images.githubusercontent.com/3787410/82675765-dcf05280-9c77-11ea-8b60-a5753d2237b1.png)

It should be fixed by someone who knows Chinese. Can anyone fix it? @nodece @GopherJ @hackerchai @kingiw @dovics

The fix should be done by correcting the Chinese translation: https://crowdin.com/translate/casbin/47/en-zhcn

**Comment by kingiw** [comment]
I can have a look at it these days.

**Comment by kingiw** [comment]
It seems there are many similar bugs in the translated docs.
https://casbin.org/docs/zh-CN/adapters
https://casbin.org/docs/zh-CN/get-started

**Comment by hsluoyz** [comment]
Oh. That's so many!

**Comment by kingiw** [comment]
@hsluoyz Could you please give me the manager access for Casbin on Crowdin? Only the project managers are able to download and build the translation project locally.

View the following link to see how to modify the roles of members in Crowdin:
https://support.crowdin.com/modifying-project-participants-roles/

**Comment by hsluoyz** [comment]
@kingiw granted.

**Comment by kingiw** [comment]
I've fixed all these bugs on Crowdin.

These bugs are triggered due to the following reason:

In the source docs, [remark-admonitions](https://github.com/elviswolcott/remark-admonitions) are used for documentation highlights. The syntax is:
```
:::note
Hello world!
:::
```
Crowdin internal translator automatically omit the newline notations and generates the new markdown files as follows:
```
:::note Hello world :::
```
However, this can not be interpreted correctly by the [remark-admonitions](https://github.com/elviswolcott/remark-admonitions).

Solution: Use `<br>` to forcibly add a newline when doing the translation.
![image](https://user-images.githubusercontent.com/22229793/82998201-045d6b80-a03a-11ea-96ea-ecf6aa671fd7.png)

**Comment by hsluoyz** [comment]
@kingiw well done! It's more complicated than I think. I thought it was just a translation error.

But for another translation language like French or Japanese, we still encounter this issue, right? I want a way to fix them all. I think we can ask https://github.com/elviswolcott/remark-admonitions to support `:::note Hello world :::`. This is easier than asking Crowdin to fix it. Can you raise an issue at: https://github.com/elviswolcott/remark-admonitions to let them fix this?

**Comment by hsluoyz** [comment]
You can see the Korean translation is also wrong: https://casbin.org/docs/ko/syntax-for-models

![image](https://user-images.githubusercontent.com/3787410/83000750-62d81900-a03d-11ea-9bd0-0cc441dc85db.png)

**Comment by hsluoyz** [comment]
We can also fire a bug at docusaurus community, to see if they want to help us or not. If they don't help, we have to contact https://github.com/elviswolcott/remark-admonitions or Crowdin by ourselves t fix it then.

**Comment by kingiw** [comment]
I'll fix the bugs in Korea right away.
As for the report report, I don't think the bug is related to docusaurus. I will raise an feature issue in remark-admonitions and a bug issue in Crowdin.

**Comment by hsluoyz** [comment]
@kingiw OK. Please don't fix the Korean bug by your own. Use it as a reproducible scenario for Crowdin guys.

**Comment by kingiw** [comment]
The Crowdin team has fixed the bugs for our projects:
> We linked the custom script to your Casbin project and now MD translation file will be exported just like expected with the newline before three colons.

I believe the issues can be close now.

**Comment by hsluoyz** [comment]
@kingiw I have given you admin for this repo. You can trigger rebuild in Travis CI:

![image](https://user-images.githubusercontent.com/3787410/83210098-8fe71180-a18c-11ea-86d2-5a233be847dd.png)

I have triggered once, but it seems Korean is still not fixed? https://casbin.org/docs/ko/syntax-for-models#%EC%A1%B0%EA%B1%B4%EC%8B%9D

**Comment by kingiw** [comment]
@hsluoyz This is because the Korean translator translate the syntax notation as well... I've fixed it now.

**Comment by hsluoyz** [comment]
@kingiw is this issue finished? If yes, please close it.

**Comment by diezcode** [comment]
This bug still exists in crowdin. How have you solved it?
from german to english it's still there....
